### PR TITLE
Problem: (CE-101) Integration tests not running on latest release

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Use Drone to run integration tests on latest v0.3 release

### CODE REVIEW

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors retry

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinlauco** [comment]
@foreseaz It's ready to be reviewed.

**Pull request merged**
