### PR TITLE
Problem: (CE-101) Integration tests not running on latest chain

### PR DESCRIPTION
**Pull request by calvinlauco**
Solution: Use Drone to run integration tests on latest chain

### CODE REVIEW

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinaco** [comment]
bors try

**Comment by calvinlauco** [comment]
bors try

**Pull request closed without merging**
